// Code generated by goctl. DO NOT EDIT.
package types

type ArticleItems struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ArticleIndexRequest struct {
	Page     int64  `form:"page"`
	PerPage  int64  `form:"perPage"`
	Keywords string `form:"keywords,optional"`
}

type ArticleIndexResponse struct {
	Items []ArticleItems `json:"items"`
	Total int64          `json:"total"`
}
