// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"myapi/article/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CORSMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/articles",
					Handler: ArticleIndexHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/articles/:id",
					Handler: ArticleDestroyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/articles/:id/edit",
					Handler: ArticleEditHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
