// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"myapi/article/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/articles",
				Handler: ArticleIndexHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/articles/:id",
				Handler: ArticleDestroyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/articles/:id/edit",
				Handler: ArticleEditHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/articles/:id",
				Handler: ArticleUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/articles",
				Handler: ArticleOptionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/articles",
				Handler: ArticleStoreHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/articles/bulkDelete/:ids",
				Handler: ArticleBulkDeleteHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
